# project
project:
  type: book
  output-dir: docs

# front matter
book:
  title: "GEOG0030 Geocomputation 2023-2024"
  author: "[Justin van Dijk](https://mappingdutchman.com/)"
  date: "9/27/2023"
  chapters:
    - part: "Module overview"
      chapters:
        - index.qmd

# output
format:
  html:
    theme: 
      flatly
    code-overflow: scroll
    code-tools: 
      source: https://github.com/jtvandijk/GEOG0030
      toggle: false
      caption: none
    code-block-bg: "#f0f0f0"
    callout-appearance: simple

# misc
title-block-banner: false
editor: source

